import { cn } from '@/lib/utils';
import Navbar from '@/components/nav';

import '@/styles/globals.css';

import { Inter } from 'next/font/google';

import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='light bg-white text-slate-900 antialiased'>
      <body
        className={cn(
          'min-h-screen bg-slate-50 pt-12 antialiased',
          inter.className
        )}
      >
        <Navbar />
        <div className='container mx-auto h-full max-w-7xl pt-12'>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
